#spring:
#  datasource:
#      url: jdbc:mysql://47.106.132.95:3306/teacherhome?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: "#scholat232"
#      max-active: 150 # 假设并发数量为100
#      min-idle: 3
#      max-idle: 150
#mybatis:
#   mapperLocations: classpath:/mapper/*.xml
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/teacherhome?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      max-active: 150 # 假设并发数量为100
      min-idle: 3h
      max-idle: 150
mybatis:
   mapperLocations: classpath:/mapper/*.xml


